ARG BASE_IMAGE=dockerhub.deepglint.com/lse/triton_trt_llm
ARG BASE_TAG=dev-base-0.1

FROM ${BASE_IMAGE}:${BASE_TAG} as base

# setup proxy and git ids
ARG proxy_val=""
ENV http_proxy=$proxy_val
ENV https_proxy=$proxy_val
ENV DG_BASE_DEV_IMAGE=${BASE_IMAGE}:${BASE_TAG}


FROM base as dgtrt_builder
WORKDIR /app
COPY dgtrt dgtrt
RUN cd /app/dgtrt && mkdir -p /app/dgtrt/build && cd /app/dgtrt/build && cmake .. && make install-python-package && cd /app && rm -rf dgtrt

FROM dgtrt_builder as trt_llm_builder

WORKDIR /app
COPY trtllm tensorrt_llm
RUN cd /app/tensorrt_llm && python3 scripts/build_wheel.py --trt_root="${TRT_ROOT}" -i -c && cd ..

FROM trt_llm_builder as trt_llm_backend_builder

WORKDIR /app/
COPY backend/inflight_batcher_llm inflight_batcher_llm
RUN cd inflight_batcher_llm && bash scripts/build.sh && cd ..

FROM trt_llm_backend_builder as final

# Install tensorrtllm backend
RUN mkdir /opt/tritonserver/backends/tensorrtllm
COPY --from=trt_llm_backend_builder /app/inflight_batcher_llm/build/libtriton_tensorrtllm.so /opt/tritonserver/backends/tensorrtllm

ENV http_proxy=""
ENV https_proxy=""