ARG BASE_IMAGE=""
ARG BASE_TAG=""

FROM ${BASE_IMAGE}:${BASE_TAG} as base

ARG LLMTK_COMMITID=""
ARG TRTLLM_COMMITID=""
ARG BACKEND_COMMITID=""
ARG OAIP_COMMITID=""
ARG IMAGE=""
ARG BASE_URL=""
ARG proxy_val=""

ENV http_proxy=$proxy_val
ENV https_proxy=$proxy_val
ENV APP_BASE_IMAGE=${BASE_URL}
ENV APP_IMAGE=${IMAGE}
ENV APP_LLMTK_COMMITID=$LLMTK_COMMITID
ENV APP_TRTLLM_COMMITID=$TRTLLM_COMMITID
ENV APP_BACKEND_COMMITID=$BACKEND_COMMITID
ENV APP_OAIP_COMMITID=$OAIP_COMMITID

WORKDIR /app
COPY . .
RUN rm -r /app/tensorrt_llm/examples && mv /app/examples /app/tensorrt_llm/
RUN bash /app/thirdparty/install.sh && rm -rf /app/thirdparty

RUN pip config set global.index-url http://mirrors.cloud.tencent.com/pypi/simple
RUN pip config set global.trusted-host mirrors.cloud.tencent.com
RUN cd vllm && pip install -e . 

ENV http_proxy=""
ENV https_proxy=""
