ARG BASE_IMAGE=""
ARG BASE_TAG=""

FROM ${BASE_IMAGE}:${BASE_TAG} as base

ARG LLMTK_COMMITID=""
ARG TRTLLM_COMMITID=""
ARG BACKEND_COMMITID=""
ARG OAIP_COMMITID=""
ARG IMAGE=""
ARG BASE_URL=""
ARG proxy_val=""

ENV http_proxy=$proxy_val
ENV https_proxy=$proxy_val
ENV APP_BASE_IMAGE=${BASE_URL}
ENV APP_IMAGE=${IMAGE}
ENV APP_LLMTK_COMMITID=$LLMTK_COMMITID
ENV APP_TRTLLM_COMMITID=$TRTLLM_COMMITID
ENV APP_BACKEND_COMMITID=$BACKEND_COMMITID
ENV APP_OAIP_COMMITID=$OAIP_COMMITID

WORKDIR /app
# thirdparty
COPY thirdparty thirdparty
RUN bash /app/thirdparty/install.sh && rm -rf /app/thirdparty

COPY script llmtk_script
COPY src llmtk_src
COPY all_models all_models
COPY oaip oaip

ENV http_proxy=""
ENV https_proxy=""